#!/usr/bin/env bash

OSES="linux darwin"

. make/include/colors.sh
. make/include/versioning.sh

set -o errexit

echo -e "${OK_COLOR}==> Building ${ERROR_COLOR}"

for OS in ${OSES}; do \
		 env GOOS=${OS} GOARCH=amd64 go build -o build/${OS}-amd64/$ARTIFACT_NAME \
		 -ldflags="-X main.version=${APP_VERSION}" \
		 ./
done

#windows is special
env GOOS=windows GOARCH=amd64 go build -o build/windows-amd64/$ARTIFACT_NAME.exe \
-ldflags="-X main.version=${APP_VERSION}" \
./

echo -e "${NO_COLOR}\c"
