#!/usr/bin/env bash

set -o errexit

. make/include/colors.sh

echo -e "${OK_COLOR}==> Vetting${ERROR_COLOR}"

go vet "$(go list -f '{{ .ImportPath }}' ./... | sed '/\/vendor\//d')"

echo -e "${NO_COLOR}\c"
